#!/usr/bin/env bash
set -Eeuo pipefail
umask 077

readonly PREFIX='[pterodactyl-locales-install]'
readonly ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)"

PANEL_INPUT=''
ARCHIVE_INPUT=''
HEALTH_URL=''
QUEUE_SERVICE='auto'
PHP_SERVICE='auto'
ASSUME_YES=0

log() { printf '%s %s\n' "$PREFIX" "$*"; }
fail() { printf '%s ERROR: %s\n' "$PREFIX" "$*" >&2; return 1; }
usage() {
    cat <<'EOF'
Usage:
  sudo ./scripts/install-release.sh --panel /var/www/pterodactyl \
      --archive /path/panel-1.15.0-localized.tar.zst [options]

Options:
  --health-url URL       Panel URL used for pre/post HTTP checks (default: APP_URL)
  --queue-service NAME   systemd queue unit (default: auto-detect pteroq.service)
  --php-service NAME     systemd PHP-FPM unit (default: auto-detect; use none for mod_php)
  --yes                  Skip the final interactive confirmation
  --help                 Show this help

The archive must have a sibling FILE.sha256 generated by build-release.sh.
No database migration is performed.
EOF
}

while (($# > 0)); do
    case "$1" in
        --panel) [[ $# -ge 2 ]] || { usage >&2; exit 2; }; PANEL_INPUT=$2; shift 2 ;;
        --archive) [[ $# -ge 2 ]] || { usage >&2; exit 2; }; ARCHIVE_INPUT=$2; shift 2 ;;
        --health-url) [[ $# -ge 2 ]] || { usage >&2; exit 2; }; HEALTH_URL=$2; shift 2 ;;
        --queue-service) [[ $# -ge 2 ]] || { usage >&2; exit 2; }; QUEUE_SERVICE=$2; shift 2 ;;
        --php-service) [[ $# -ge 2 ]] || { usage >&2; exit 2; }; PHP_SERVICE=$2; shift 2 ;;
        --yes) ASSUME_YES=1; shift ;;
        --help) usage; exit 0 ;;
        *) usage >&2; printf '%s ERROR: unknown option: %s\n' "$PREFIX" "$1" >&2; exit 2 ;;
    esac
done

[[ ${EUID:-$(id -u)} -eq 0 ]] || { fail 'run this installer with sudo or as root'; exit 1; }
[[ -n "$PANEL_INPUT" && -n "$ARCHIVE_INPUT" ]] || { usage >&2; exit 2; }

for command in awk basename chown chmod cmp cp curl date df dirname du find flock getent grep install mv node php realpath rm runuser sha256sum sleep stat systemctl tar; do
    command -v "$command" >/dev/null || { fail "required command is absent: $command"; exit 1; }
done

readonly PANEL_DIR="$(realpath -e -- "$PANEL_INPUT")"
readonly PANEL_PARENT="$(dirname -- "$PANEL_DIR")"
readonly ARCHIVE="$(realpath -e -- "$ARCHIVE_INPUT")"
readonly CHECKSUM_FILE="$ARCHIVE.sha256"
readonly STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
readonly STAGE_DIR="$PANEL_PARENT/.pterodactyl-locales-stage-$STAMP"
readonly ROLLBACK_DIR="$PANEL_PARENT/.pterodactyl-locales-rollback-$STAMP"
readonly FAILED_DIR="$PANEL_PARENT/.pterodactyl-locales-failed-$STAMP"
readonly LOCK_FILE="$PANEL_PARENT/.pterodactyl-locales.lock"

[[ "$PANEL_DIR" != / && "$PANEL_DIR" != "$PANEL_PARENT" ]] || { fail 'refusing an unsafe Panel path'; exit 1; }
[[ ! -L "$PANEL_INPUT" ]] || { fail 'Panel path must not be a symbolic link'; exit 1; }
[[ -f "$PANEL_DIR/artisan" && -f "$PANEL_DIR/.env" ]] || { fail 'Panel artisan or .env is absent'; exit 1; }
[[ -d "$PANEL_DIR/storage" && -f "$PANEL_DIR/vendor/autoload.php" ]] || { fail 'Panel storage or Composer vendor tree is absent'; exit 1; }
[[ -f "$CHECKSUM_FILE" ]] || { fail "release checksum is absent: $CHECKSUM_FILE"; exit 1; }
[[ ! -L "$ARCHIVE" && ! -L "$CHECKSUM_FILE" ]] || { fail 'release and checksum must not be symbolic links'; exit 1; }

archive_mode=$(stat -Lc '%a' -- "$ARCHIVE")
(( (8#$archive_mode & 8#022) == 0 )) || { fail 'release archive must not be writable by group or other users'; exit 1; }
checksum_mode=$(stat -Lc '%a' -- "$CHECKSUM_FILE")
(( (8#$checksum_mode & 8#022) == 0 )) || { fail 'release checksum must not be writable by group or other users'; exit 1; }

exec 9>"$LOCK_FILE"
flock -n 9 || { fail 'another locale deployment holds the Panel lock'; exit 1; }

for path in "$STAGE_DIR" "$ROLLBACK_DIR" "$FAILED_DIR"; do
    [[ ! -e "$path" ]] || { fail "transaction path already exists: $path"; exit 1; }
done

readonly EXPECTED_VERSION="$(php -r '$v=json_decode(file_get_contents($argv[1]), true, 512, JSON_THROW_ON_ERROR); echo $v["version"];' "$ROOT/upstream.json")"
grep -Fq "'version' => '$EXPECTED_VERSION'" "$PANEL_DIR/config/app.php" \
    || { fail "live Panel is not the supported version $EXPECTED_VERSION"; exit 1; }

mapfile -t checksum_lines <"$CHECKSUM_FILE"
[[ ${#checksum_lines[@]} -eq 1 ]] || { fail 'release checksum must contain exactly one record'; exit 1; }
checksum_hash=${checksum_lines[0]%% *}
checksum_name=${checksum_lines[0]#"$checksum_hash"}
checksum_name=${checksum_name#  }
[[ "$checksum_hash" =~ ^[a-fA-F0-9]{64}$ ]] || { fail 'release checksum hash is invalid'; exit 1; }
[[ "$checksum_name" == "$(basename -- "$ARCHIVE")" ]] || { fail 'release checksum names a different archive'; exit 1; }
actual_hash=$(sha256sum -- "$ARCHIVE" | awk '{print $1}')
[[ "${actual_hash,,}" == "${checksum_hash,,}" ]] || { fail 'release archive checksum does not match'; exit 1; }
archive_listing=$(tar --zstd -tf "$ARCHIVE")
if grep -Eq '(^/|(^|/)\.\.(/|$))' <<<"$archive_listing"; then
    fail 'release archive contains an unsafe path'; exit 1
fi

if [[ -z "$HEALTH_URL" ]]; then
    HEALTH_URL=$(awk -F= '
        $1 == "APP_URL" {
            sub(/^[^=]*=/, "");
            gsub(/^['"'"']|['"'"']$/, "");
            print;
            exit
        }
    ' "$PANEL_DIR/.env")
fi
[[ "$HEALTH_URL" =~ ^https?://[^[:space:]]+$ ]] || { fail 'set a valid --health-url or APP_URL'; exit 1; }
HEALTH_URL=${HEALTH_URL%/}

if [[ "$QUEUE_SERVICE" == auto ]]; then
    if systemctl cat pteroq.service >/dev/null 2>&1; then
        QUEUE_SERVICE='pteroq.service'
    else
        fail 'could not auto-detect pteroq.service; pass --queue-service NAME'
        exit 1
    fi
elif [[ "$QUEUE_SERVICE" != none && "$QUEUE_SERVICE" != *.service ]]; then
    QUEUE_SERVICE="$QUEUE_SERVICE.service"
fi

if [[ "$PHP_SERVICE" == auto ]]; then
    php_minor=$(php -r 'echo PHP_MAJOR_VERSION, ".", PHP_MINOR_VERSION;')
    php_candidates=()
    for candidate in "php$php_minor-fpm.service" php-fpm.service; do
        if systemctl is-active --quiet "$candidate" 2>/dev/null; then php_candidates+=("$candidate"); fi
    done
    if ((${#php_candidates[@]} == 1)); then
        PHP_SERVICE=${php_candidates[0]}
    elif ((${#php_candidates[@]} == 0)); then
        fail 'could not auto-detect an active PHP-FPM service; pass --php-service NAME or --php-service none'
        exit 1
    else
        fail "multiple PHP services are active; choose one with --php-service: ${php_candidates[*]}"
        exit 1
    fi
elif [[ "$PHP_SERVICE" != none && "$PHP_SERVICE" != *.service ]]; then
    PHP_SERVICE="$PHP_SERVICE.service"
fi

[[ "$QUEUE_SERVICE" == none ]] || systemctl is-active --quiet "$QUEUE_SERVICE" \
    || { fail "queue service is inactive: $QUEUE_SERVICE"; exit 1; }
[[ "$PHP_SERVICE" == none ]] || systemctl is-active --quiet "$PHP_SERVICE" \
    || { fail "PHP service is inactive: $PHP_SERVICE"; exit 1; }

readonly PANEL_USER="$(stat -Lc '%U' -- "$PANEL_DIR/artisan")"
readonly PANEL_UID="$(stat -Lc '%u' -- "$PANEL_DIR/artisan")"
readonly PANEL_GID="$(stat -Lc '%g' -- "$PANEL_DIR/artisan")"
readonly PANEL_MODE="$(stat -Lc '%a' -- "$PANEL_DIR")"
[[ "$PANEL_USER" != UNKNOWN ]] && getent passwd "$PANEL_UID" >/dev/null \
    || { fail 'Panel code owner is not a usable local account'; exit 1; }

run_panel() { runuser -u "$PANEL_USER" -- php "$1/artisan" "${@:2}"; }
http_code() { curl -sS -o /dev/null -w '%{http_code}' --connect-timeout 10 --max-time 30 "$1"; }

baseline_code=$(http_code "$HEALTH_URL")
[[ "$baseline_code" =~ ^(2|3)[0-9][0-9]$ ]] \
    || { fail "Panel baseline returned HTTP $baseline_code at $HEALTH_URL"; exit 1; }

live_bytes=$(du -sb -- "$PANEL_DIR" | awk '{print $1}')
available_bytes=$(df -PB1 -- "$PANEL_PARENT" | awk 'NR == 2 {print $4}')
(( available_bytes > live_bytes + 536870912 )) \
    || { fail 'insufficient free space for a complete staged tree and rollback reserve'; exit 1; }

if ((ASSUME_YES == 0)); then
    printf '%s Panel: %s\n' "$PREFIX" "$PANEL_DIR"
    printf '%s Release: %s\n' "$PREFIX" "$ARCHIVE"
    printf '%s Queue service: %s; PHP service: %s\n' "$PREFIX" "$QUEUE_SERVICE" "$PHP_SERVICE"
    printf '%s The complete previous Panel will be retained at: %s\n' "$PREFIX" "$ROLLBACK_DIR"
    printf '%s No database migration will be run. Continue? [y/N] ' "$PREFIX"
    read -r confirmation
    [[ "$confirmation" == y || "$confirmation" == Y ]] || { log 'Cancelled without changes.'; exit 0; }
fi

maintenance_started=0
old_panel_moved=0
new_panel_activated=0

restore_previous_panel() {
    local rollback_failed=0 code=000 attempt
    set +e
    trap - ERR INT TERM

    if ((maintenance_started == 0)); then
        rm -rf -- "$STAGE_DIR"
        return 0
    fi

    log 'Deployment failed; restoring the complete previous Panel tree.'
    [[ "$QUEUE_SERVICE" == none ]] || systemctl stop "$QUEUE_SERVICE" >/dev/null 2>&1 || true
    if ((new_panel_activated == 1)) && [[ -d "$PANEL_DIR" ]]; then
        mv -- "$PANEL_DIR" "$FAILED_DIR" || rollback_failed=1
        chmod 0700 "$FAILED_DIR" 2>/dev/null || true
    fi
    if ((old_panel_moved == 1)) && [[ -d "$ROLLBACK_DIR" ]]; then
        mv -- "$ROLLBACK_DIR" "$PANEL_DIR" || rollback_failed=1
        chmod "$PANEL_MODE" "$PANEL_DIR" || rollback_failed=1
    fi
    if [[ -f "$PANEL_DIR/artisan" ]]; then
        run_panel "$PANEL_DIR" view:clear >/dev/null 2>&1 || rollback_failed=1
        run_panel "$PANEL_DIR" config:clear >/dev/null 2>&1 || rollback_failed=1
        run_panel "$PANEL_DIR" route:clear >/dev/null 2>&1 || rollback_failed=1
        run_panel "$PANEL_DIR" up >/dev/null 2>&1 || rollback_failed=1
    else
        rollback_failed=1
    fi
    [[ "$PHP_SERVICE" == none ]] || systemctl restart "$PHP_SERVICE" || rollback_failed=1
    [[ "$QUEUE_SERVICE" == none ]] || systemctl start "$QUEUE_SERVICE" || rollback_failed=1
    for ((attempt=1; attempt<=30; attempt++)); do
        if code=$(http_code "$HEALTH_URL" 2>/dev/null) && [[ "$code" =~ ^(2|3)[0-9][0-9]$ ]]; then break; fi
        sleep 1
    done
    [[ "$code" =~ ^(2|3)[0-9][0-9]$ ]] || rollback_failed=1
    if ((rollback_failed != 0)); then
        printf '%s ERROR: rollback is incomplete; inspect %s and %s\n' "$PREFIX" "$ROLLBACK_DIR" "$FAILED_DIR" >&2
        return 1
    fi
    log "Previous Panel restored; failed replacement retained at: $FAILED_DIR"
}

on_error() { local code=$?; trap - ERR INT TERM; restore_previous_panel || true; exit "$code"; }
on_signal() { local code=$1; trap - ERR INT TERM; restore_previous_panel || true; exit "$code"; }
trap on_error ERR
trap 'on_signal 130' INT
trap 'on_signal 143' TERM

log 'Preparing the replacement tree while the live Panel remains online.'
install -d -o root -g root -m 0755 "$STAGE_DIR"
tar --zstd -xf "$ARCHIVE" --no-same-owner --no-same-permissions -C "$STAGE_DIR"
[[ -f "$STAGE_DIR/artisan" && -f "$STAGE_DIR/.pterodactyl-locales/release.json" \
    && -f "$STAGE_DIR/.pterodactyl-locales/upstream-files.json" ]] \
    || fail 'localized release manifest or artisan is absent'
[[ ! -e "$STAGE_DIR/.env" ]] || fail 'release archive unexpectedly contains .env'
if find "$STAGE_DIR" -type l -print -quit | grep -q .; then fail 'release archive unexpectedly contains a symbolic link'; fi
grep -Fq "'version' => '$EXPECTED_VERSION'" "$STAGE_DIR/config/app.php" || fail 'release Panel version is wrong'
grep -Fq "\"upstream\": \"$EXPECTED_VERSION\"" "$STAGE_DIR/.pterodactyl-locales/release.json" \
    || fail 'localization release targets a different Panel version'
node "$ROOT/tools/tree-manifest.mjs" check "$PANEL_DIR" "$STAGE_DIR/.pterodactyl-locales/upstream-files.json"
cmp -s "$PANEL_DIR/composer.lock" "$STAGE_DIR/composer.lock" \
    || fail 'live Composer lock differs from the clean supported release; remove customizations or deploy manually'

chown -R "$PANEL_UID:$PANEL_GID" "$STAGE_DIR"
rm -rf -- "$STAGE_DIR/vendor" "$STAGE_DIR/storage" "$STAGE_DIR/bootstrap/cache"
cp -a -- "$PANEL_DIR/vendor" "$STAGE_DIR/vendor"
cp -a -- "$PANEL_DIR/storage" "$STAGE_DIR/storage"
cp -a -- "$PANEL_DIR/.env" "$STAGE_DIR/.env"
install -d -m "$(stat -Lc '%a' -- "$PANEL_DIR/bootstrap/cache")" "$STAGE_DIR/bootstrap/cache"
chown --reference="$PANEL_DIR/bootstrap/cache" "$STAGE_DIR/bootstrap/cache"
if [[ -d "$PANEL_DIR/public/favicons" ]]; then
    rm -rf -- "$STAGE_DIR/public/favicons"
    cp -a -- "$PANEL_DIR/public/favicons" "$STAGE_DIR/public/favicons"
fi
chmod --reference="$PANEL_DIR/artisan" "$STAGE_DIR/artisan"
chmod "$PANEL_MODE" "$STAGE_DIR"

for php_file in \
    app/Http/Controllers/Base/LanguageController.php \
    app/Http/Requests/Base/LocaleRequest.php \
    app/Traits/Helpers/AvailableLanguages.php \
    routes/base.php; do
    php -l "$STAGE_DIR/$php_file" >/dev/null
done
run_panel "$STAGE_DIR" --version >/dev/null
run_panel "$STAGE_DIR" route:list --name=account.language --no-ansi | grep -Fq account.language \
    || fail 'language route is not registered in staging'

log 'Entering brief maintenance mode; Wings and game containers remain online.'
maintenance_started=1
run_panel "$PANEL_DIR" down
[[ "$QUEUE_SERVICE" == none ]] || systemctl stop "$QUEUE_SERVICE"

old_panel_moved=1
mv -- "$PANEL_DIR" "$ROLLBACK_DIR"
chmod 0700 "$ROLLBACK_DIR"
new_panel_activated=1
mv -- "$STAGE_DIR" "$PANEL_DIR"

run_panel "$PANEL_DIR" package:discover --ansi
run_panel "$PANEL_DIR" view:clear
run_panel "$PANEL_DIR" config:clear
run_panel "$PANEL_DIR" route:clear
run_panel "$PANEL_DIR" queue:restart
[[ "$PHP_SERVICE" == none ]] || systemctl restart "$PHP_SERVICE"
run_panel "$PANEL_DIR" up
[[ "$QUEUE_SERVICE" == none ]] || systemctl start "$QUEUE_SERVICE"

[[ "$PHP_SERVICE" == none ]] || systemctl is-active --quiet "$PHP_SERVICE"
[[ "$QUEUE_SERVICE" == none ]] || systemctl is-active --quiet "$QUEUE_SERVICE"
post_code=000
if ! post_code=$(http_code "$HEALTH_URL"); then
    fail "localized Panel did not respond at $HEALTH_URL"
fi
[[ "$post_code" =~ ^(2|3)[0-9][0-9]$ ]] || fail "localized Panel returned HTTP $post_code"
run_panel "$PANEL_DIR" route:list --name=account.language --no-ansi | grep -Fq account.language \
    || fail 'language route disappeared after activation'

trap - ERR INT TERM
log 'Localized Panel deployed and validated successfully.'
log "Complete previous Panel retained for rollback at: $ROLLBACK_DIR"
log 'Review all locales in a private browser session before deleting that rollback tree.'
